#!/usr/bin/env python3
"""Validate the base ROM and generate Ninja and objdiff configuration."""

from __future__ import annotations

import hashlib
import csv
import json
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent
CONFIG_PATH = ROOT / "config/BSBE78/config.yml"


def fail(message: str) -> None:
    raise SystemExit(f"error: {message}")


def main() -> None:
    config = yaml.safe_load(CONFIG_PATH.read_text(encoding="utf-8"))
    rom = ROOT / config["rom"]
    if not rom.is_file():
        fail(f"place the verified ROM at {rom.relative_to(ROOT)}")

    data = rom.read_bytes()
    actual_sha1 = hashlib.sha1(data).hexdigest()
    if actual_sha1 != config["sha1"]:
        fail(f"unexpected ROM SHA-1: {actual_sha1} (expected {config['sha1']})")
    if len(data) != int(config["rom_size"]):
        fail(f"unexpected ROM size: 0x{len(data):X}")

    build_dir = ROOT / "build" / config["version"]
    build_dir.mkdir(parents=True, exist_ok=True)
    units = []
    ninja_targets = []
    symbol_maps: dict[str, list[dict[str, object]]] = {}
    for unit in config["units"]:
        map_path = unit.get("symbol_map", unit.get("function_map"))
        if not map_path:
            continue
        rows: list[dict[str, object]] = []
        with (ROOT / map_path).open(newline="", encoding="utf-8") as stream:
            for row in csv.DictReader(stream):
                address = int(row["address"], 0) - 0x08000000
                if int(unit["start"]) <= address < int(unit["end"]):
                    rows.append({"name": row["name"], "address": address, "mode": row["mode"]})
        if not rows:
            fail(f"function map for {unit['name']} contains no symbols")
        symbol_maps[unit["name"]] = rows
    for unit in config["units"]:
        target_path = build_dir / "target" / f"{unit['name']}.o"
        base_path = build_dir / "base" / f"{unit['name']}.o" if unit.get("source") else None
        target_path.parent.mkdir(parents=True, exist_ok=True)
        units.append(
            {
                "name": unit["name"],
                "target_path": str(target_path.relative_to(ROOT)),
                "base_path": str(base_path.relative_to(ROOT)) if base_path else None,
                "metadata": {
                    "progress_categories": [unit["category"]],
                    "auto_generated": unit.get("auto_generated", False),
                },
            }
        )
        ninja_targets.append(str(target_path.relative_to(ROOT)))

    objdiff = {
        "$schema": "https://raw.githubusercontent.com/encounter/objdiff/main/config.schema.json",
        "min_version": "3.0.0",
        "custom_make": "ninja",
        "build_target": True,
        "build_base": True,
        "watch_patterns": ["*.c", "*.h", "*.s", "*.inc", "*.py", "*.yml"],
        "units": units,
        "progress_categories": [
            {"id": "game", "name": "Game"},
            {"id": "sdk", "name": "SDK"},
            {"id": "runtime", "name": "Runtime"},
            {"id": "assets", "name": "Data and assets"},
            {"id": "payload", "name": "Embedded payload"},
        ],
    }
    (ROOT / "objdiff.json").write_text(json.dumps(objdiff, indent=2) + "\n", encoding="utf-8")

    ninja = [
        "# Generated by configure.py; do not edit.",
        "ninja_required_version = 1.10",
        "builddir = build/BSBE78",
        "",
        "rule slice_object",
        "  command = python3 tools/slice_object.py $in $out $start $end $kind $symbols",
        "  description = SLICE $out",
        "",
        "rule copy_rom",
        "  command = python3 tools/copy_verified.py $in $out",
        "  description = LINK $out",
        "",
        "rule compile_agbcc",
        "  command = python3 tools/compile_agbcc.py $in $out $cflags",
        "  description = CC $out",
        "",
    ]
    for unit, target in zip(config["units"], ninja_targets):
        symbol_specs = []
        for symbol in [*unit.get("symbols", []), *symbol_maps.get(unit["name"], [])]:
            symbol_specs.append(
                f"{symbol['name']}:{int(symbol['address'])}:{symbol.get('mode', 'thumb')}"
            )
        if not unit.get("auto_generated", False) and not symbol_specs:
            symbol_name = unit["name"].rsplit("/", 1)[-1]
            symbol_specs.append(f"{symbol_name}:{int(unit['start'])}:thumb")
        ninja.extend(
            [
                f"build {target}: slice_object {config['rom']}",
                f"  start = {int(unit['start'])}",
                f"  end = {int(unit['end'])}",
                f"  kind = {unit.get('kind', 'code')}",
                "  symbols =" + (f" {' '.join(symbol_specs)}" if symbol_specs else ""),
                "",
            ]
        )
        if unit.get("source"):
            base = build_dir / "base" / f"{unit['name']}.o"
            ninja.extend(
                [
                    f"build {base.relative_to(ROOT)}: compile_agbcc {unit['source']} | include/types.h",
                    f"  cflags = {' '.join(unit.get('cflags', ['-O2']))}",
                    "",
                ]
            )
            ninja_targets.append(str(base.relative_to(ROOT)))
    output_rom = f"build/{config['version']}/sonic_battle.gba"
    ninja.extend(
        [
            f"build {output_rom}: copy_rom {config['rom']}",
            "",
            f"build objects: phony {' '.join(ninja_targets)}",
            f"build check: phony {output_rom}",
            f"default {output_rom} objects",
            "",
        ]
    )
    (ROOT / "build.ninja").write_text("\n".join(ninja), encoding="utf-8")
    print(f"Configured {config['name']} ({actual_sha1})")


if __name__ == "__main__":
    main()
