#!/usr/bin/env python3
"""Validate the base ROM and generate Ninja and objdiff configuration."""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent
CONFIG_PATH = ROOT / "config/BSBE78/config.yml"


def fail(message: str) -> None:
    raise SystemExit(f"error: {message}")


def main() -> None:
    config = yaml.safe_load(CONFIG_PATH.read_text(encoding="utf-8"))
    rom = ROOT / config["rom"]
    if not rom.is_file():
        fail(f"place the verified ROM at {rom.relative_to(ROOT)}")

    data = rom.read_bytes()
    actual_sha1 = hashlib.sha1(data).hexdigest()
    if actual_sha1 != config["sha1"]:
        fail(f"unexpected ROM SHA-1: {actual_sha1} (expected {config['sha1']})")
    if len(data) != int(config["rom_size"]):
        fail(f"unexpected ROM size: 0x{len(data):X}")

    build_dir = ROOT / "build" / config["version"]
    build_dir.mkdir(parents=True, exist_ok=True)
    units = []
    ninja_targets = []
    for unit in config["units"]:
        target_path = build_dir / "target" / f"{unit['name']}.o"
        target_path.parent.mkdir(parents=True, exist_ok=True)
        units.append(
            {
                "name": unit["name"],
                "target_path": str(target_path.relative_to(ROOT)),
                "base_path": None,
                "metadata": {
                    "progress_categories": [unit["category"]],
                    "auto_generated": unit.get("auto_generated", False),
                },
            }
        )
        ninja_targets.append(str(target_path.relative_to(ROOT)))

    objdiff = {
        "$schema": "https://raw.githubusercontent.com/encounter/objdiff/main/config.schema.json",
        "min_version": "3.0.0",
        "custom_make": "ninja",
        "build_target": True,
        "build_base": True,
        "watch_patterns": ["*.c", "*.h", "*.s", "*.inc", "*.py", "*.yml"],
        "units": units,
        "progress_categories": [
            {"id": "game", "name": "Game"},
            {"id": "sdk", "name": "SDK"},
            {"id": "runtime", "name": "Runtime"},
        ],
    }
    (ROOT / "objdiff.json").write_text(json.dumps(objdiff, indent=2) + "\n", encoding="utf-8")

    ninja = [
        "# Generated by configure.py; do not edit.",
        "ninja_required_version = 1.10",
        "builddir = build/BSBE78",
        "",
        "rule slice_object",
        "  command = python3 tools/slice_object.py $in $out $start $end",
        "  description = SLICE $out",
        "",
        "rule copy_rom",
        "  command = python3 tools/copy_verified.py $in $out",
        "  description = LINK $out",
        "",
    ]
    for unit, target in zip(config["units"], ninja_targets):
        ninja.extend(
            [
                f"build {target}: slice_object {config['rom']}",
                f"  start = {int(unit['start'])}",
                f"  end = {int(unit['end'])}",
                "",
            ]
        )
    output_rom = f"build/{config['version']}/sonic_battle.gba"
    ninja.extend(
        [
            f"build {output_rom}: copy_rom {config['rom']}",
            "",
            f"build objects: phony {' '.join(ninja_targets)}",
            f"build check: phony {output_rom}",
            f"default {output_rom} objects",
            "",
        ]
    )
    (ROOT / "build.ninja").write_text("\n".join(ninja), encoding="utf-8")
    print(f"Configured {config['name']} ({actual_sha1})")


if __name__ == "__main__":
    main()
